# Generated by Django 4.1.7 on 2023-03-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0004_meep'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
